apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-lake-api
  namespace: delta-lake
  labels:
    app: delta-lake-api
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delta-lake-api
  template:
    metadata:
      labels:
        app: delta-lake-api
        component: api
    spec:
      containers:
      - name: api
        image: delta-lake-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: delta-lake-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: delta-lake-config
              key: LOG_LEVEL
        - name: DATABRICKS_HOST
          valueFrom:
            secretKeyRef:
              name: delta-lake-secrets
              key: DATABRICKS_HOST
        - name: DATABRICKS_TOKEN
          valueFrom:
            secretKeyRef:
              name: delta-lake-secrets
              key: DATABRICKS_TOKEN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: delta-lake-api-service
  namespace: delta-lake
  labels:
    app: delta-lake-api
spec:
  selector:
    app: delta-lake-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: delta-lake-api-hpa
  namespace: delta-lake
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delta-lake-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
