apiVersion: v1
kind: ConfigMap
metadata:
  name: delta-lake-config
  namespace: delta-lake
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DATABRICKS_CATALOG: "main"
  DATABRICKS_SCHEMA: "default"
  # Add other non-sensitive configuration here
